num_words_to_generate: 75
seed: 1

lm_model:
    size: gpt2-medium
    type: cond
    temperature: 1
    top_k: 10
    top_p: 0.9
    gm_scale: 0.9
    fuse_with_real_probs: true
    early_stop: 10

attribute_controller:
    attribute_losses: [
        {
            type: bow,
            topic: science,
            weight: 1
        } 
    ]
    window_len: 4
    kl_scale: 0.01
    num_grad_steps: 3
    step_size: 0.02
    gamma: 1.5
