num_words_to_generate: 75
seed: 1

lm_model:
    size: gpt2-medium
    type: cond
    temperature: 1.0
    top_k: 10
    top_p: 0.9
    gm_scale: 0.9
    fuse_with_real_probs: True
    early_stop: 20

attribute_controller:
    attribute_losses: [
        {
            type: bow,
            topic: science,
            weight: 1
        },
        {
            type: bow,
            topic: religion,
            weight: 1
        } 
    ]
    window_len: 4
    kl_scale: 0.01
    num_grad_steps: 4
    step_size: 0.01
    gamma: 1.5
